function ProvablyFairExplainedKenoGames() {
  return (
    <div className="[&_p]:text-base [&_p]:leading-7 [&_img]:mx-auto space-y-[10px] [&_h3]:text-[2rem] [&_h3]:mb-[16px]">
      <h1 className="bg-image-clip-text text-[2.5rem] mb-[30px]">Provably Fair on our Keno Games</h1>

      <p className="font-bold !text-2xl leading-9 mx-auto !mb-[50px]">
        Our Provably Fair system allows all keno players to test the fairness of their games by verifying the results.
        Numbers are drawn from a randomly assorted list. Your influence in the game is in choosing the position within
        the list from which the 20 numbers are drawn.
      </p>

      <h3>1. We create a random assortment of the numbers and show you its "fingerprint"</h3>
      <p>
        Before the 20 numbers are drawn, our server randomly sorts all 80 numbers using an algorithm based on the
        Mersenne Twister random number generator.
      </p>
      <p>
        The randomly assorted list of numbers and an additional random number (this is called the server seed) is then
        hashed and presented to you as the server hash.
      </p>
      <img className="!my-[40px] w-[400px] max-w-[80%]" src="/assistance/slot-next-game-server-hash.png" alt="" />
      <p className="!text-sm italic text-center">
        Server seed generated by our server is hashed and presented to you as server hash on the &quot;Next game&quot; tab.
      </p>

      <h3>2. Choose the starting draw position</h3>
      <p>
        This is when you step in. You can now set the client seed. In the game menu under Provably Fair&apos;s Next game
        tab you can select a number from 0 to 79. This sets the starting position from which the 20 numbers will be
        drawn.
      </p>
      <img className="!my-[40px] w-[400px] max-w-[80%]" src="/assistance/client-seed-2.png" alt="" />

      <h3>3. Drawing the numbers</h3>
      <p>
        When you press the PLAY button, the numbers are sequentially drawn from the randomly assorted list of numbers,
        starting from the position you selected.
      </p>
      <img className="!my-[40px] w-[500px] max-w-[80%]" src="/assistance/blazing-wilds.png" alt="" />
      <p className="!text-sm italic text-center">
        As client seed was set to &quot;3&quot;, the numbers are drawn from the fourth position.
      </p>

      <h3>4. Verifying the result</h3>
      <p>
        Once the game is finished, you can check its fairness in the game menu under Provably Fair&apos;s Last game tab.
        You will be presented with the original server seed, server hash (the hashed server seed) and the client seed.
      </p>
      <p>
        You can use an independent website to verify that the server seed was truly presented to you as the server hash
        by hashing the server seed on this independent website. If the hashed results are identical, the game was fair
        according to Provably Fair concept. This means no one tampered with the result.
      </p>
      <img className="!my-[40px] w-[400px] max-w-[80%]" src="/assistance/client-seed-6.png" alt="" />

      <h3>5. Play again</h3>
      <p>
        You can now set the client seed again in the game menu under Provably Fair&apos;s Next game tab, or we will
        automatically pick a random number for you.
      </p>
      <img className="!my-[40px] w-[400px] max-w-[80%]" src="/assistance/client-seed-6.png" alt="" />

      <hr className="border-t border-[#5c5e60] my-[56px]" />

      <h2 className="bg-image-clip-text text-[2.5rem] uppercase">More About Provably Fair</h2>
      <p className="!mb-[20px]">
        Interested in delving deeper into this topic? Explore the comprehensive Provably Fair article series, which not
        only covers the fundamentals and advantages but also delves into the intricacies of the technology.
      </p>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 !mt-[24px]">
        <article className="bg-[#d0d2d3] p-5 space-y-3">
          <h4 className="text-[2rem] leading-9 font-semibold text-[#2f3237]">Provably Fair 1: An Introduction</h4>
          <p className="!text-[1.4rem] !leading-7 text-[#4b4f54]">
            Have you ever questioned the fairness of an online casino? How can you be sure that the games aren&apos;t...
          </p>
          <a className="text-[#0093dd] font-semibold" href="#">Read More</a>
        </article>
        <article className="bg-[#d0d2d3] p-5 space-y-3">
          <h4 className="text-[2rem] leading-9 font-semibold text-[#2f3237]">Provably Fair 2: The Basics &amp; Hashing</h4>
          <p className="!text-[1.4rem] !leading-7 text-[#4b4f54]">
            In the first part of this series, we explored the potential risks involved in gaming and discussed th...
          </p>
          <a className="text-[#0093dd] font-semibold" href="#">Read More</a>
        </article>
        <article className="bg-[#d0d2d3] p-5 space-y-3">
          <h4 className="text-[2rem] leading-9 font-semibold text-[#2f3237]">Provably Fair 3: Diverse Implementations</h4>
          <p className="!text-[1.4rem] !leading-7 text-[#4b4f54]">
            In the previous parts, we&apos;ve delved into the definition of Provably Fair, the pros and cons of the...
          </p>
          <a className="text-[#0093dd] font-semibold" href="#">Read More</a>
        </article>
      </div>
    </div>
  )
}

export default ProvablyFairExplainedKenoGames
